import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

const newake = localFont({
  src: './fonts/Newake.otf',
  display: 'swap',
  variable: '--font-newake',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{
      scrollSnapType: 'y mandatory',
    }}>
      <body className={`${newake.variable}`}>{children}</body>
    </html>
  )
}
